/* Generated By:JavaCC: Do not edit this line. calculatorConstants.java */
package arts.g.d.talkcalc.jj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface calculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR_BIT = 2;
  /** RegularExpression Id. */
  int XOR_BIT = 3;
  /** RegularExpression Id. */
  int AND_BIT = 4;
  /** RegularExpression Id. */
  int RSHIFT_BIT = 5;
  /** RegularExpression Id. */
  int LSHIFT_BIT = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULTIPLY = 9;
  /** RegularExpression Id. */
  int DIVIDE = 10;
  /** RegularExpression Id. */
  int MOD = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int INTEGER_NUMBER = 15;
  /** RegularExpression Id. */
  int FLOATING_NUMBER = 16;
  /** RegularExpression Id. */
  int DIGITS = 17;
  /** RegularExpression Id. */
  int SIN = 18;
  /** RegularExpression Id. */
  int COS = 19;
  /** RegularExpression Id. */
  int TAN = 20;
  /** RegularExpression Id. */
  int ASIN = 21;
  /** RegularExpression Id. */
  int ACOS = 22;
  /** RegularExpression Id. */
  int ATAN = 23;
  /** RegularExpression Id. */
  int TORADIANS = 24;
  /** RegularExpression Id. */
  int TODEGREES = 25;
  /** RegularExpression Id. */
  int EXP = 26;
  /** RegularExpression Id. */
  int LOG = 27;
  /** RegularExpression Id. */
  int LOG10 = 28;
  /** RegularExpression Id. */
  int SQRT = 29;
  /** RegularExpression Id. */
  int CBRT = 30;
  /** RegularExpression Id. */
  int CEIL = 31;
  /** RegularExpression Id. */
  int FLOOR = 32;
  /** RegularExpression Id. */
  int RINT = 33;
  /** RegularExpression Id. */
  int ABS = 34;
  /** RegularExpression Id. */
  int SIGNUM = 35;
  /** RegularExpression Id. */
  int SINH = 36;
  /** RegularExpression Id. */
  int COSH = 37;
  /** RegularExpression Id. */
  int TANH = 38;
  /** RegularExpression Id. */
  int POW = 39;
  /** RegularExpression Id. */
  int ATAN2 = 40;
  /** RegularExpression Id. */
  int MAX = 41;
  /** RegularExpression Id. */
  int MIN = 42;
  /** RegularExpression Id. */
  int HYPOT = 43;
  /** RegularExpression Id. */
  int PI = 44;
  /** RegularExpression Id. */
  int MATH_E = 45;
  /** RegularExpression Id. */
  int DATE = 46;
  /** RegularExpression Id. */
  int FDATE = 47;
  /** RegularExpression Id. */
  int COMMA = 48;
  /** RegularExpression Id. */
  int HEX_NUMBER = 49;
  /** RegularExpression Id. */
  int BIN_NUMBER = 50;
  /** RegularExpression Id. */
  int STRING = 51;
  /** RegularExpression Id. */
  int FLOATING_POINT = 52;
  /** RegularExpression Id. */
  int EXPONENT = 53;
  /** RegularExpression Id. */
  int EOL = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "<INTEGER_NUMBER>",
    "<FLOATING_NUMBER>",
    "<DIGITS>",
    "<SIN>",
    "<COS>",
    "<TAN>",
    "<ASIN>",
    "<ACOS>",
    "<ATAN>",
    "<TORADIANS>",
    "<TODEGREES>",
    "<EXP>",
    "<LOG>",
    "<LOG10>",
    "<SQRT>",
    "<CBRT>",
    "<CEIL>",
    "<FLOOR>",
    "<RINT>",
    "<ABS>",
    "<SIGNUM>",
    "<SINH>",
    "<COSH>",
    "<TANH>",
    "<POW>",
    "<ATAN2>",
    "<MAX>",
    "<MIN>",
    "<HYPOT>",
    "<PI>",
    "<MATH_E>",
    "<DATE>",
    "<FDATE>",
    "\",\"",
    "<HEX_NUMBER>",
    "<BIN_NUMBER>",
    "<STRING>",
    "<FLOATING_POINT>",
    "<EXPONENT>",
    "<EOL>",
  };

}
